### ISSUE TITLE
Complete individual reflections before IRL

### ISSUE THREAD

**Issue by amyashida** [GSA/public-benefits-studio#105]
Each studio staff member will identify the possible futures they see and the questions that will inform which path they think is best. 

Come from your personal/discipline perspective. 

Feel free to answer individually then bring over or write directly into the doc. Whichever works for you personally. 

This will help us come to the IRL with informed opinions and known gaps that we need to resolve in order to be on the same page moving forward.

Estimated complete: EOD 8/13

**Comment by rahearn** [comment]
The template doc to collect questions can be found here: https://docs.google.com/document/d/18tlyJCmUKX22MRqk_YDmJ1mIO6wDjiR2pCq_Fq3up80/edit#

**Comment by amyashida** [comment]
Em is adding some detail re: component 2 questions

**Comment by alexpandel** [comment]
process question @amyashida / @tdlowden — folks indicated in our IRL retro that they'd like to come back to the questions from this homework; should we repurpose this issue to include "revisit these questions post-IRL"? Or close this issue and make a separate one just for that?
