### ISSUE TITLE
DUE 8/12 Document our current understanding of authority and paths to work with states

### ISSUE THREAD

**Issue by amyashida** [GSA/public-benefits-studio#108]
So that as a group we have the same information and we can roadmap the path to working with states and make plans for initial partnerships. 

Target date: EOD 8/12

**Comment by amyashida** [comment]
Tim will lead this - need to make sure he's in this project so he can be added to this card

**Comment by tdlowden** [comment]
https://docs.google.com/document/d/1-oLuC75VkuyIUc8chS1DmGviId5afIPfFxYWO3C8ASo/edit
