### ISSUE TITLE
DUE 8/19 Set up first steps meeting with OGC Tech division to talk IGCA and FCSF

### ISSUE THREAD

**Issue by tdlowden** [GSA/public-benefits-studio#117]

**Comment by tdlowden** [comment]
Email sent from Amy to Dan N and Micah P. Meeting to take place 9/7 or 9/8

**Comment by alexpandel** [comment]
just scheduled this! should we make a separate issue for prep for that meeting, or just reframe this issue to include prep for the meeting?

**Comment by tdlowden** [comment]
I'll set up a new issue and close this. Thanks!
