### ISSUE TITLE
Prep for 9/7 call with OGC

### ISSUE THREAD

**Issue by tdlowden** [GSA/public-benefits-studio#118]
- [x] Schedule meeting between Tim, Amy, Alex to discuss desired outcomes
- [x] Create a questions doc we can send them ahead of time, if necessary
- [x] incorporate feedback from Allison
- [x] Send to OGC in advance of meeting

**Comment by tdlowden** [comment]
Questions doc sent to Allison H for feedback. After we receive word from her, we'll pass to OGC.

**Comment by alexpandel** [comment]
took a stab at incorporating most of Allison's feedback, but there are a few last bits that need work, and then we should prob send it to OGC by EOD tomorrow (Friday), so they have time to review? gonna untag myself since I'm prob out tomorrow, you cool to take over the finish line @amyashida ?
