### ISSUE TITLE
take first pass at synthesizing pilot goals

### ISSUE THREAD

**Issue by rahearn** [GSA/public-benefits-studio#120]
So that we're clear on what we're trying to learn, to help us in identifying the right partners/use cases

**To do:**
- [x] synthesize our IRL brainstorm around pilot goals into a Google Doc
- [x] share with others for feedback before 8/25 team time
- [ ] decide on top 2-3 pilot goals as a team at 8/25 team time

**Comment by tdlowden** [comment]
Doc for reference where I took first pass at 3 goals: https://docs.google.com/document/d/1LSsVx0nG5jQkvKSXfG-Mwfw7RoNbiB7ZVlcIKwKxlcg/edit#
