### ISSUE TITLE
Clarify team roles/task-sharing norms

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#132]
So that we know what's normally in scope for our individual roles, and what our task-sharing norms are

To do:
- [x] @amyashida take a first pass at defining work areas & drop in Slack for prep before convo
- [x] all of us do some pre-thinking before convo
- [x] @amyashida facilitate convo
- [x] set up follow-up time to continue discussion
- [x] define "done" for this task; scope 9/8 discussion  to get to "done" w/ team
- [x] make sure any resulting decisions/next steps are documented

**Comment by alexpandel** [comment]
next step here is to plan a follow up discussion (currently scheduled for 9/8). @amyashida has a conflict at that time, so I'm taking the lead on shaping that, and pulling in @em-herrick for support! @em-herrick, I'll find some time for us to put our heads together next week in prep for the 9/8 sesh

**Comment by em-herrick** [comment]
@amyashida and @alexpandel I think it would be really helpful for you all to refine the "General Studio Work Areas" section of the mural specifically focused on your individual focus areas to better understand what questions we might go to who with.

I could also see us using the grey cards related to outreach to guide our planning convo next week.
