### ISSUE TITLE
pull pilot definition info into one doc (goals, use cases, & partner criteria)

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#135]

**Comment by tdlowden** [comment]
Combined into https://docs.google.com/document/d/1LSsVx0nG5jQkvKSXfG-Mwfw7RoNbiB7ZVlcIKwKxlcg/edit#


![Image](https://user-images.githubusercontent.com/6556888/187444659-10ea319e-8f83-4118-aced-4a6cf430274c.png)
