### ISSUE TITLE
define "min specs" of MVP

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#136]
So that we have something we can use to prioritize work more effectively with the 10x GNS team (e.g., clarity around bidirectionality, email, and API development being nice-to-haves; clarifying what _are_ must haves [including things the 10x team may have not been thinking about yet; UX things, etc])

**Comment by tdlowden** [comment]
Awaiting feedback from team before closing out.

**Comment by amyashida** [comment]
Looped into #119 - we discussed as a team on 9/1
