### ISSUE TITLE
Review previous IGCA proposals & draft ours

### ISSUE THREAD

**Issue by tdlowden** [GSA/public-benefits-studio#161]
To do:

- [x] @tdlowden take 1st pass
- [x] @amyashida review and add context
- [x] @alexpandel review
- [ ] @tdlowden @alexpandel & Allison: decide who else in TTS to get feedback from (Vicki M?), & get that feedback

**Comment by tdlowden** [comment]
Email to Allison Hutchings to try to source the previous packages.

**Comment by tdlowden** [comment]
Reply from Allison on 9/13. We have 18F's docs but not yet Logins.

**Comment by tdlowden** [comment]
Allison replied 9/15 with templates. I reviewed and took a pass at constructing our justification, minus the cost aspect, [here](https://docs.google.com/document/d/1d-4c-Tm-YQ72-xiU0EDz1E-s5s3zLVwmJ5lnd8LdwpA/edit#).

**Comment by tdlowden** [comment]
@amyashida @alexpandel interested in your thoughts on what I constructed here. May be cleaner for me just to remove the vestigial login stuff altogether.

**Comment by amyashida** [comment]
I will take a look at this today!

**Comment by amyashida** [comment]
Added comments - reviewing w/ Allison today.

**Comment by tdlowden** [comment]
Action items from 10/5 meeting with Allison:

 - Allison will talk to Raylene
 - Allison will feel out the OMB situation (possibly Ben Skidmore)
 - [ ] AMY: Add a blurb about the LE ties
 - [ ] AMY: Add a bit more detail around expected financial cost
 - [ ] Pivot the doc slightly to talk about the unique aspects of Notify/what benefit the Studio would provide absent of a tech product
 - [ ] Share doc with Dan N and Micah P

**Comment by amyashida** [comment]
I added my edits to the doc! @tdlowden do you want to work with @alexpandel and Allison to collect further TTS feedback while I'm out?

**Comment by tdlowden** [comment]
sent to OGC 10/19. 

@alexpandel and @tdlowden will find time to discuss who else within TTS to get 👀 on the doc. Is the next step after that Nina/Jackie/LBS? There is not a set process for shepherding a doc like this

**Comment by amyashida** [comment]
I think this is done - tracking now in #167.
