### ISSUE TITLE
Set up Studio AWS needs

### ISSUE THREAD

**Issue by rahearn** [GSA/public-benefits-studio#162]
https://handbook.tts.gsa.gov/launching-software/infrastructure/#cloud-service-provider-csp-sandbox-accounts

Tasks:

- [ ] receive credentials for new program account
- [ ] https://github.com/GSA/notifications-api/issues/70

**Comment by rahearn** [comment]
I sent a request for sandbox access on 9/15

**Comment by rahearn** [comment]
I sent a request for program access on 9/16

**Comment by rahearn** [comment]
@tdlowden and I had a call with tech portfolio on 9/23. We both have sandbox access now and John should be setting up an organization for notify on 9/26

**Comment by amyashida** [comment]
I'm on this now - waiting for procurement steps!

**Comment by tdlowden** [comment]
@rahearn will follow up with John J on GovCloud
