### ISSUE TITLE
Create outreach packet

### ISSUE THREAD

**Issue by em-herrick** [GSA/public-benefits-studio#174]
So that we have materials to send out to help people understand who we are, what we are working on, what our timelines are and how to engage with us

**Comment by em-herrick** [comment]
Currently adapting original benefit studio one pager into a [Notify 2-pager.](https://docs.google.com/document/d/1Y2US886_iv64RL0cs3GEzDyg0KQb2vjUFGYTH9xyYes/edit#)

@tdlowden would love to have your eyes on this specifically around how we talk about the product.

Open Question:
How to shift the original "about the studio" framing, is this still how we want to intro ourselves?

**Comment by em-herrick** [comment]
@tdlowden @amyashida @alexpandel this doc is ready for all of your reviews! Hoping to align on last edits at our Outreach Sync on Monday

**Comment by tdlowden** [comment]
ok took a second pass and added some language!
