### ISSUE TITLE
Ask WIC for a pre-pilot interview /feedback

### ISSUE THREAD

**Issue by em-herrick** [GSA/public-benefits-studio#175]
so that we continue to keep this lead warm while continuing to get feedback on pre-pilot hypotheses

**Comment by amyashida** [comment]
I'm going to wait for this to see if the are connected to the 0-5 work.

**Comment by amyashida** [comment]
Closing - we sent them responses[ via this doc](https://docs.google.com/document/d/1cfket0tciNtntYSTiUMDbbYb6lG47B_37Xxtfactbas/edit)
