### ISSUE TITLE
set up Notify demo for MD&P team

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#178]
So that the TTS BD team understands where Notify is at and what we're looking for in pilot partners, so they can keep their ears to the ground on potential oppts in their calls w/ agencies.

To do:
- [x] decide on who should lead demo/meeting on our side
- [x] schedule call with Phil, Tom & Devika (+ Laurie as optional), plus whomevers leading on our side (plus A+A as optional)
- [ ] prep for convo
- [ ] have meeting/capture any next steps!

**Comment by tdlowden** [comment]
Slack message sent to Phil/MD&P team 9/27

**Comment by tdlowden** [comment]
invite sent. looks like Devika has a conflict at that time.
