### ISSUE TITLE
work with OA on Flexion BPA order

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#189]
So that we can bring on more support for getting Notify to pilot!

To do:

- [x] submit OA intake form
- [x] @alexpandel loop in Steven on email to Jackie M to see what's next
- [ ] update card as new tasks emerge :)

**Comment by stvnrlly** [comment]
I'm going to move this over to https://github.com/GSA/notifications-admin/issues/236, so feel free to close after the loop-in email

**Comment by alexpandel** [comment]
sounds good, done!
