### ISSUE TITLE
Help organize/templatize our "about us" documentation

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#190]

**Comment by alexpandel** [comment]
hi @DanRaudonisTC & @aleidafernandez! realize we could use this as a "test" issue for figuring out our Github flow with y'all — depending on how far along y'all are with this task when we chat next week, we can add some of the context about this task and track remaining progress in here

**Comment by aleidafernandez** [comment]
Hey! Sounds good. We'll poke around here

**Comment by alexpandel** [comment]
closing this issue in favor of the overlapping #192!
