### ISSUE TITLE
start prepping hiring process for Studio team members

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#26]
- [x] Start an interview question bank
- [x] Update announcement to reflect recent thinking
- [x] Get answers from Ashley about setting up a selection panel
- [x] Meet w/ John Yuda to learn more about policy role
- [x] sketch out recommendations around selection process & hiring order of operations
- [x] set up time to talk with Karen Trebon re: getting the process started

**Comment by amyashida** [comment]
[Interview bank ](https://docs.google.com/document/d/1gc7PGw9hTZCsf_Pdo6uKCs1kgZfAnLwSxPU5keCbWuE/edit#)started by pulling questions from other interview guides + converting skills needed into questions

**Comment by amyashida** [comment]
Sketched out my[ understanding of the process](https://docs.google.com/document/d/1_DT8zxKebAtKKBQ-CnyhL1ORfNNzvxfVq-miENgxJ2U/edit) and what AP and I can contribute to or not.
