### ISSUE TITLE
Draft ARP proposal

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#29]
**Why:** to make this thing real!

**Definition of done:**
- [x] if needed, ask AM for US Digital Corps example
- [x] start fleshing out [proposal doc](https://docs.google.com/document/d/14aA8ffEpVpv65q4eZbE2x-vnfWApfpP5/edit)
- [x] get @fedrampashley's eyes on it
- [x] check some of our #s Qs w/ Jackie
- [x] submit!

**Comment by amyashida** [comment]
this is drafted - waiting on AM for a thumbs up before submitting
