### ISSUE TITLE
Get feedback on initial outreach approach

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#34]
**Why:** So that the info doesn't get lost in a Mural :)

**Definition of done:**
- [x] write up doc about tentative outreach plan based on [Mural](https://app.mural.co/t/gsa6/m/gsa6/1644266715566/61b4756d1110ac607a2d70f08ecaeb055541748f?sender=alexandrapandel) (highlight open questions; what we know will be clarified once a problem area is chosen, etc)
- [x] draft specific approach for first bet
- [x] get feedback on approach

**Comment by amyashida** [comment]
General outline[ in this doc](https://docs.google.com/document/d/1hy73vYHyEFQUHav7HMh16Vzpi1h2Wx4_3uMcsSrRn0o/edit#heading=h.wn2sr84nibxn)

**Comment by alexpandel** [comment]
@amyashida are we still working on this? or is this task done for now?
