### ISSUE TITLE
Get intro blog post published

### ISSUE THREAD

**Issue by alexpandel** [GSA/public-benefits-studio#79]
**Why:** To get something linkable out in the world that says we exist and what we do!

**To do:**

- [x] meet with Star to decide on comms approach, & start on approvals process
- [x] take stab at flipping around order of blog post
- [x] share back with Star for review
- [x] AP send to writing lab
- [x] meet with Jake Parcell re: next steps
- [x] talk to Sarah C re: sign up form options
- [x] @alexpandel check that Tim can access our Qualtrics account
- [x] @em-herrick and/or @tdlowden take pass at updating [post content](https://docs.google.com/document/d/1JklA0gpr7MZc4ToDz0ga4fXnrh5fqOCSLSg_oDuYf6o/edit#heading=h.hv1a4s20a5n9)
- [x] @alexpandel do final content review, then tag in next reviewers for approval 
- [x] talk to OGC about linking to outside sources
- [x] email source selection criteria to DG, OGC & Outreach folks 
- [ ] @alexpandel get update from Ammie on expected pub date

**Comment by alexpandel** [comment]
just scheduled a meeting with Toni for tomorrow to unblock this

**Comment by alexpandel** [comment]
@tdlowden just asked about Qualtrics access for you; I expect we'll hear back tomorrowish!

**Comment by tdlowden** [comment]
I'm in with Qualtrics. @alexpandel, we may want to chat about what we want in this interest form and/or considerations we need to have regarding asking questions to people?

**Comment by tdlowden** [comment]
Alex will follow up w/ Ammie

**Comment by em-herrick** [comment]
@em-herrick to update screenshot

**Comment by tdlowden** [comment]
@alexpandel @em-herrick any further updates here?

**Comment by alexpandel** [comment]
@em-herrick or @tdlowden, any chance one of you could swap out the screenshot for the new one with the "U.S. Notify" logo? I'm working through Toni's edits right now and that should be the last thing 🤞

**Comment by em-herrick** [comment]
@alexpandel done!! New screenshot added

**Comment by alexpandel** [comment]
just video chatted with Toni to clarify next steps; she _should_ be ready to sign off today, and then I believe this moves to the next level of approval, which it looks like is Ammie from DigitalGov. @amyashida I tagged you in as backup on this in case they need anything from us next week while I'm out

**Comment by alexpandel** [comment]
IT'S LIVE, WOOOOOO!!! https://digital.gov/2023/02/07/collaborate-with-the-tts-public-benefits-studio/
