### ISSUE TITLE
Update ecosystem map

### ISSUE THREAD

**Issue by amyashida** [GSA/public-benefits-studio#90]
Pull in updates from coworking time to[ Mural](https://app.mural.co/t/gsa6/m/gsa6/1652823232746/96bdd15877bbb10d09733697f2d30d4e146111e0?sender=amyashida5338)

- [x] AA to digitize
- [x] AP and SR review
- [x] AP to prep to share with team during remote kickoff

**Comment by alexpandel** [comment]
calling this done for now, though I know we want to iterate further. will make a new issue for that when it becomes relevant again
